---
abstract: 'Add Pastedance service to App::Nopaste'
author:
  - 'Danijel Tasov <data@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste-Service-Pastedance
provides:
  App::Nopaste::Service::Pastedance:
    file: lib/App/Nopaste/Service/Pastedance.pm
    version: 0.04
requires:
  App::Nopaste: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/datamuc/App-Nopaste-Service-Pastedance
version: 0.04
